service:
  env: "local"
  name: "reaction service"
  version: "v1"
  instance: "reaction1"
grpc:
  port: 2343
http:
  port: 2323
storage:
  hostname: "localhost"
  port: 3000
  namespace: "ReactionService"
tracing:
  enabled: true
  endpoint: "localhost:4318"