env: "local"
grpc:
  port: 2342
  timeout: 30s
storage:
  addr: "localhost:6379"
  password: ""
  db: 0
reaction_service:
  url: "http://localhost:2343"
messaging:
  servers: "localhost:29092"
  group: "geo4"
  topic: "profile.updates"