service:
  env: "local"
  name: "geo service"
  version: "v1"
  instance: "geo1"
grpc:
  port: 2342
  timeout: 30s
http:
  port: 2322
storage:
  addr: "localhost:6379"
  password: ""
  db: 0
reaction_service:
  endpoint: "http://localhost:2343"
messaging:
  servers: "localhost:29092"
  group: "geo4"
  topic: "profile.updates"
tracing:
  enabled: true
  endpoint: "localhost:4318"