// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.0--rc1
// source: geo_service.proto

package tinderpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeedByLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeoZoneId int64 `protobuf:"varint,1,opt,name=geo_zone_id,json=geoZoneId,proto3" json:"geo_zone_id,omitempty"`
}

func (x *GetFeedByLocationRequest) Reset() {
	*x = GetFeedByLocationRequest{}
	mi := &file_geo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedByLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedByLocationRequest) ProtoMessage() {}

func (x *GetFeedByLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedByLocationRequest.ProtoReflect.Descriptor instead.
func (*GetFeedByLocationRequest) Descriptor() ([]byte, []int) {
	return file_geo_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetFeedByLocationRequest) GetGeoZoneId() int64 {
	if x != nil {
		return x.GeoZoneId
	}
	return 0
}

type GetFeedByLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiles []*ProfileDto `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	// Types that are assignable to Error:
	//
	//	*GetFeedByLocationResponse_UnexpectedServerError
	//	*GetFeedByLocationResponse_NoNewProfiles
	Error isGetFeedByLocationResponse_Error `protobuf_oneof:"error"`
}

func (x *GetFeedByLocationResponse) Reset() {
	*x = GetFeedByLocationResponse{}
	mi := &file_geo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedByLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedByLocationResponse) ProtoMessage() {}

func (x *GetFeedByLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedByLocationResponse.ProtoReflect.Descriptor instead.
func (*GetFeedByLocationResponse) Descriptor() ([]byte, []int) {
	return file_geo_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetFeedByLocationResponse) GetProfiles() []*ProfileDto {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (m *GetFeedByLocationResponse) GetError() isGetFeedByLocationResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (x *GetFeedByLocationResponse) GetUnexpectedServerError() *UnexpectedServerError {
	if x, ok := x.GetError().(*GetFeedByLocationResponse_UnexpectedServerError); ok {
		return x.UnexpectedServerError
	}
	return nil
}

func (x *GetFeedByLocationResponse) GetNoNewProfiles() *NoNewProfilesError {
	if x, ok := x.GetError().(*GetFeedByLocationResponse_NoNewProfiles); ok {
		return x.NoNewProfiles
	}
	return nil
}

type isGetFeedByLocationResponse_Error interface {
	isGetFeedByLocationResponse_Error()
}

type GetFeedByLocationResponse_UnexpectedServerError struct {
	UnexpectedServerError *UnexpectedServerError `protobuf:"bytes,2,opt,name=unexpected_server_error,json=unexpectedServerError,proto3,oneof"`
}

type GetFeedByLocationResponse_NoNewProfiles struct {
	NoNewProfiles *NoNewProfilesError `protobuf:"bytes,3,opt,name=no_new_profiles,json=noNewProfiles,proto3,oneof"`
}

func (*GetFeedByLocationResponse_UnexpectedServerError) isGetFeedByLocationResponse_Error() {}

func (*GetFeedByLocationResponse_NoNewProfiles) isGetFeedByLocationResponse_Error() {}

type ProfileDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileId   int64    `protobuf:"varint,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PhotoUrls   []string `protobuf:"bytes,4,rep,name=photo_urls,json=photoUrls,proto3" json:"photo_urls,omitempty"`
}

func (x *ProfileDto) Reset() {
	*x = ProfileDto{}
	mi := &file_geo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileDto) ProtoMessage() {}

func (x *ProfileDto) ProtoReflect() protoreflect.Message {
	mi := &file_geo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileDto.ProtoReflect.Descriptor instead.
func (*ProfileDto) Descriptor() ([]byte, []int) {
	return file_geo_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileDto) GetProfileId() int64 {
	if x != nil {
		return x.ProfileId
	}
	return 0
}

func (x *ProfileDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProfileDto) GetPhotoUrls() []string {
	if x != nil {
		return x.PhotoUrls
	}
	return nil
}

type ChangeLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeoZoneId int64 `protobuf:"varint,1,opt,name=geo_zone_id,json=geoZoneId,proto3" json:"geo_zone_id,omitempty"`
}

func (x *ChangeLocationRequest) Reset() {
	*x = ChangeLocationRequest{}
	mi := &file_geo_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLocationRequest) ProtoMessage() {}

func (x *ChangeLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geo_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLocationRequest.ProtoReflect.Descriptor instead.
func (*ChangeLocationRequest) Descriptor() ([]byte, []int) {
	return file_geo_service_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeLocationRequest) GetGeoZoneId() int64 {
	if x != nil {
		return x.GeoZoneId
	}
	return 0
}

type ChangeLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Error:
	//
	//	*ChangeLocationResponse_UnexpectedServerError
	//	*ChangeLocationResponse_ProfileIdNotFound
	//	*ChangeLocationResponse_GeoZoneIdNotFound
	Error isChangeLocationResponse_Error `protobuf_oneof:"error"`
}

func (x *ChangeLocationResponse) Reset() {
	*x = ChangeLocationResponse{}
	mi := &file_geo_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLocationResponse) ProtoMessage() {}

func (x *ChangeLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geo_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLocationResponse.ProtoReflect.Descriptor instead.
func (*ChangeLocationResponse) Descriptor() ([]byte, []int) {
	return file_geo_service_proto_rawDescGZIP(), []int{4}
}

func (m *ChangeLocationResponse) GetError() isChangeLocationResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (x *ChangeLocationResponse) GetUnexpectedServerError() *UnexpectedServerError {
	if x, ok := x.GetError().(*ChangeLocationResponse_UnexpectedServerError); ok {
		return x.UnexpectedServerError
	}
	return nil
}

func (x *ChangeLocationResponse) GetProfileIdNotFound() *ProfileIdNotFoundError {
	if x, ok := x.GetError().(*ChangeLocationResponse_ProfileIdNotFound); ok {
		return x.ProfileIdNotFound
	}
	return nil
}

func (x *ChangeLocationResponse) GetGeoZoneIdNotFound() *GeoZoneIdNotFoundError {
	if x, ok := x.GetError().(*ChangeLocationResponse_GeoZoneIdNotFound); ok {
		return x.GeoZoneIdNotFound
	}
	return nil
}

type isChangeLocationResponse_Error interface {
	isChangeLocationResponse_Error()
}

type ChangeLocationResponse_UnexpectedServerError struct {
	UnexpectedServerError *UnexpectedServerError `protobuf:"bytes,1,opt,name=unexpected_server_error,json=unexpectedServerError,proto3,oneof"`
}

type ChangeLocationResponse_ProfileIdNotFound struct {
	ProfileIdNotFound *ProfileIdNotFoundError `protobuf:"bytes,2,opt,name=profile_id_not_found,json=profileIdNotFound,proto3,oneof"`
}

type ChangeLocationResponse_GeoZoneIdNotFound struct {
	GeoZoneIdNotFound *GeoZoneIdNotFoundError `protobuf:"bytes,3,opt,name=geo_zone_id_not_found,json=geoZoneIdNotFound,proto3,oneof"`
}

func (*ChangeLocationResponse_UnexpectedServerError) isChangeLocationResponse_Error() {}

func (*ChangeLocationResponse_ProfileIdNotFound) isChangeLocationResponse_Error() {}

func (*ChangeLocationResponse_GeoZoneIdNotFound) isChangeLocationResponse_Error() {}

// Profiles wasn't found in requested geo zone
type NoNewProfilesError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoNewProfilesError) Reset() {
	*x = NoNewProfilesError{}
	mi := &file_geo_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoNewProfilesError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoNewProfilesError) ProtoMessage() {}

func (x *NoNewProfilesError) ProtoReflect() protoreflect.Message {
	mi := &file_geo_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoNewProfilesError.ProtoReflect.Descriptor instead.
func (*NoNewProfilesError) Descriptor() ([]byte, []int) {
	return file_geo_service_proto_rawDescGZIP(), []int{5}
}

type ProfileIdNotFoundError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProfileIdNotFoundError) Reset() {
	*x = ProfileIdNotFoundError{}
	mi := &file_geo_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileIdNotFoundError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileIdNotFoundError) ProtoMessage() {}

func (x *ProfileIdNotFoundError) ProtoReflect() protoreflect.Message {
	mi := &file_geo_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileIdNotFoundError.ProtoReflect.Descriptor instead.
func (*ProfileIdNotFoundError) Descriptor() ([]byte, []int) {
	return file_geo_service_proto_rawDescGZIP(), []int{6}
}

type GeoZoneIdNotFoundError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GeoZoneIdNotFoundError) Reset() {
	*x = GeoZoneIdNotFoundError{}
	mi := &file_geo_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoZoneIdNotFoundError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoZoneIdNotFoundError) ProtoMessage() {}

func (x *GeoZoneIdNotFoundError) ProtoReflect() protoreflect.Message {
	mi := &file_geo_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoZoneIdNotFoundError.ProtoReflect.Descriptor instead.
func (*GeoZoneIdNotFoundError) Descriptor() ([]byte, []int) {
	return file_geo_service_proto_rawDescGZIP(), []int{7}
}

var File_geo_service_proto protoreflect.FileDescriptor

var file_geo_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x65, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x1a, 0x14, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x42, 0x79, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0b, 0x67, 0x65, 0x6f, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x67, 0x65, 0x6f, 0x5a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x22, 0xf3, 0x01,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x74, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x74,
	0x6f, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x57, 0x0a, 0x17, 0x75,
	0x6e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x15, 0x75,
	0x6e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x44, 0x0a, 0x0f, 0x6e, 0x6f, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x74, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x6f, 0x4e,
	0x65, 0x77, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x80, 0x01, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44,
	0x74, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x55, 0x72, 0x6c, 0x73, 0x22, 0x37, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0b, 0x67, 0x65, 0x6f, 0x5f, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x67, 0x65, 0x6f, 0x5a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x22,
	0xa1, 0x02, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x17, 0x75, 0x6e,
	0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x15, 0x75, 0x6e,
	0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x51, 0x0a, 0x14, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x49, 0x64, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x48, 0x00, 0x52, 0x11, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x4e, 0x6f,
	0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x52, 0x0a, 0x15, 0x67, 0x65, 0x6f, 0x5f, 0x7a, 0x6f,
	0x6e, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x6f, 0x5a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x11, 0x67, 0x65, 0x6f, 0x5a, 0x6f, 0x6e, 0x65,
	0x49, 0x64, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x4e, 0x6f, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x6f, 0x5a, 0x6f, 0x6e, 0x65, 0x49, 0x64,
	0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xb7, 0x01,
	0x0a, 0x0a, 0x47, 0x65, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x2e, 0x74, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65,
	0x65, 0x64, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x74, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x65, 0x65, 0x64, 0x42, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x74, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x74, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x70, 0x62, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_geo_service_proto_rawDescOnce sync.Once
	file_geo_service_proto_rawDescData = file_geo_service_proto_rawDesc
)

func file_geo_service_proto_rawDescGZIP() []byte {
	file_geo_service_proto_rawDescOnce.Do(func() {
		file_geo_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_geo_service_proto_rawDescData)
	})
	return file_geo_service_proto_rawDescData
}

var file_geo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_geo_service_proto_goTypes = []any{
	(*GetFeedByLocationRequest)(nil),  // 0: tinder.GetFeedByLocationRequest
	(*GetFeedByLocationResponse)(nil), // 1: tinder.GetFeedByLocationResponse
	(*ProfileDto)(nil),                // 2: tinder.ProfileDto
	(*ChangeLocationRequest)(nil),     // 3: tinder.ChangeLocationRequest
	(*ChangeLocationResponse)(nil),    // 4: tinder.ChangeLocationResponse
	(*NoNewProfilesError)(nil),        // 5: tinder.NoNewProfilesError
	(*ProfileIdNotFoundError)(nil),    // 6: tinder.ProfileIdNotFoundError
	(*GeoZoneIdNotFoundError)(nil),    // 7: tinder.GeoZoneIdNotFoundError
	(*UnexpectedServerError)(nil),     // 8: tinder.UnexpectedServerError
}
var file_geo_service_proto_depIdxs = []int32{
	2, // 0: tinder.GetFeedByLocationResponse.profiles:type_name -> tinder.ProfileDto
	8, // 1: tinder.GetFeedByLocationResponse.unexpected_server_error:type_name -> tinder.UnexpectedServerError
	5, // 2: tinder.GetFeedByLocationResponse.no_new_profiles:type_name -> tinder.NoNewProfilesError
	8, // 3: tinder.ChangeLocationResponse.unexpected_server_error:type_name -> tinder.UnexpectedServerError
	6, // 4: tinder.ChangeLocationResponse.profile_id_not_found:type_name -> tinder.ProfileIdNotFoundError
	7, // 5: tinder.ChangeLocationResponse.geo_zone_id_not_found:type_name -> tinder.GeoZoneIdNotFoundError
	0, // 6: tinder.GeoService.GetFeedByLocation:input_type -> tinder.GetFeedByLocationRequest
	3, // 7: tinder.GeoService.ChangeLocation:input_type -> tinder.ChangeLocationRequest
	1, // 8: tinder.GeoService.GetFeedByLocation:output_type -> tinder.GetFeedByLocationResponse
	4, // 9: tinder.GeoService.ChangeLocation:output_type -> tinder.ChangeLocationResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_geo_service_proto_init() }
func file_geo_service_proto_init() {
	if File_geo_service_proto != nil {
		return
	}
	file_error_messages_proto_init()
	file_geo_service_proto_msgTypes[1].OneofWrappers = []any{
		(*GetFeedByLocationResponse_UnexpectedServerError)(nil),
		(*GetFeedByLocationResponse_NoNewProfiles)(nil),
	}
	file_geo_service_proto_msgTypes[4].OneofWrappers = []any{
		(*ChangeLocationResponse_UnexpectedServerError)(nil),
		(*ChangeLocationResponse_ProfileIdNotFound)(nil),
		(*ChangeLocationResponse_GeoZoneIdNotFound)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_geo_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geo_service_proto_goTypes,
		DependencyIndexes: file_geo_service_proto_depIdxs,
		MessageInfos:      file_geo_service_proto_msgTypes,
	}.Build()
	File_geo_service_proto = out.File
	file_geo_service_proto_rawDesc = nil
	file_geo_service_proto_goTypes = nil
	file_geo_service_proto_depIdxs = nil
}
