service:
  env: "local"
  name: "geo service"
  version: "v1"
  instance: "geo1"
grpc:
  port: 2342
http:
  port: 2322
storage:
  addr: "tndr-redis:6379"
  password: ""
  db: 0
reaction_service:
  endpoint: "http://tndr-reaction-service:2343"
messaging:
  servers: "tndr-kafka:9092"
  group: "geo1"
  topic: "profile.updates"
tracing:
  enabled: true
  endpoint: "tndr-jaeger:4318"