version: '3.1'

services:
  geo-service:
    image: tndr-geo-service
    build: 
      context: ../../src/Geo
      dockerfile: ../../src/Geo/Dockerfile
    container_name: tndr-geo-service
    ports:
      - "2342:2342"
      - "2322:2322"
    volumes:
      - ./config.yaml:/config.yaml
    depends_on:
      kafka:
        condition: service_healthy

  redis:
    container_name: tndr-redis
    image: redis:alpine
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "8379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      
  jaeger:
    container_name: tndr-jaeger
    image: jaegertracing/all-in-one
    restart: unless-stopped
    ports:
      - "14268:14268"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  zookeeper:
    container_name: tndr-zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - "4181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami

  kafka:
    container_name: tndr-kafka
    image: bitnami/kafka:latest
    ports:
      - "38092:29092"
      - "11092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=tndr-zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CLIENT://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://tndr-kafka:9092,CLIENT://127.0.0.1:38092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_MESSAGE_MAX_BYTES=1048588
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list"]
      start_period: 5s
      interval: 5s
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
  kafka_data: